jay-monitor:
  image: '192.168.200.90/longen/jay'
  ports:
    - "9999:9999"
  volumes:
    - '/mnt/nas/jay-cluster-py3/monitor:/app'
  command: ./statistic_monitor.py
  restart: always
  environment:
    - MONGODB_SERVER=${MongoDB_Server}
    - REDIS_HOST=${Redis_Host}
    - KAFKA_HOSTS=${Kafka_Hosts}
    - broker_url=${Broker_Url}
    - LOG_LEVEL=${Log_Level}
    - LOG_STDOUT=True
    - SERVER_CLASS=ForkingWSGIServer
    - DEBUG=False

controller-monitor:
  image: '192.168.200.90/longen/jay'
  volumes:
    - '/mnt/nas/jay-cluster-py3/monitor:/app'
  command: ./controller_monitor.py
  restart: always
  environment:
    - MONGODB_SERVER=${MongoDB_Server}
    - REDIS_HOST=${Redis_Host}
    - KAFKA_HOSTS=${Kafka_Hosts}
    - broker_url=${Broker_Url}
    - LOG_LEVEL=${Log_Level}
    - LOG_STDOUT=True
    - IMAGE_PROCESSES=20

captcha-monitor:
  image: '192.168.200.90/longen/jay'
  volumes:
    - '/mnt/nas/jay-cluster-py3/monitor:/app'
  command: ./captcha_monitor.py
  restart: always
  environment:
    - KAFKA_HOSTS=${Kafka_Hosts}
    - LOG_LEVEL=${Log_Level}
    - LOG_STDOUT=True

celery-monitor:
  image: '192.168.200.90/longen/jay'
  volumes:
    - '/mnt/nas/jay-cluster-py3/monitor:/app'
  command: ./celery_monitor.py
  restart: always
  environment:
    - MONGODB_SERVER=${MongoDB_Server}
    - REDIS_HOST=${Redis_Host}
    - KAFKA_HOSTS=${Kafka_Hosts}
    - broker_url=${Broker_Url}
    - LOG_LEVEL=${Log_Level}
    - LOG_STDOUT=True

amazon-spider:
  image: '192.168.200.90/longen/jay'
  volumes:
    - '/mnt/nas/jay-cluster-py3:/app'
  command: scrapy crawl amazon
  restart: always
  environment:
    - REDIS_HOST=${Redis_Host}
    - KAFKA_HOSTS=${Kafka_Hosts}
    - SC_LOG_LEVEL=INFO

zappos-spider:
  image: '192.168.200.90/longen/jay'
  volumes:
    - '/mnt/nas/jay-cluster-py3:/app'
  command: scrapy crawl zappos
  restart: always
  environment:
    - REDIS_HOST=${Redis_Host}
    - KAFKA_HOSTS=${Kafka_Hosts}
    - SC_LOG_LEVEL=INFO
